services:
  chatty-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - redis
    restart: always
    env_file:
      - stack.env

  redis:
    image: redis:7
    volumes:
      - ${REDIS_DATA:-./redis_data}:/data
    restart: always
    ports:
      - '6370:6379'

volumes:
  redis_data:
    driver: local
